clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  vue-build:
    image: node
    commands:
      - make
      - git diff --exit-code js/bruteforcesettings.js
    when:
      matrix:
        TESTS: vue-build
matrix:
  include:
    - TESTS: vue-build

branches: [ master ]
